version: '3.1'
services:
  testing:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - blog
    depends_on:
      blog:
        condition: service_healthy
  blog:
    image: ghcr.io/blog/blogalong:${TAG:-main}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health/readiness"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - 8090:8090
