apiVersion: auth.blog.run/v1alpha1
kind: AuthProvider
metadata:
  name: local
  labels:
    auth.blog.run/auth-binding: "false"
    auth.blog.run/privileged: "true"
  finalizers:
    - system-protection
spec:
  displayName: Local
  enabled: true
  description: Built-in authentication for Blog.
  logo: https://halo.run/logo
  website: https://halo.run
  authenticationUrl: /login
