apiVersion: v1alpha1
kind: "Role"
metadata:
  name: anonymous
  labels:
    blog.run/role-template: "true"
    blog.run/hidden: "true"
  annotations:
    rbac.authorization.blog.run/dependencies: |
      [ "role-template-own-permissions", "role-template-public-apis" ]
rules:
  - apiGroups: [ "api.blog.run" ]
    resources: [ "comments", "comments/reply" ]
    verbs: [ "create", "get", "list" ]
  - apiGroups: [ "api.blog.run" ]
    resources: [ "*" ]
    verbs: [ "*" ]
  - apiGroups: [ "api.console.blog.run" ]
    resources: [ "users" ]
    resourceNames: [ "-" ]
    verbs: [ "get" ]
  - nonResourceURLs: [ "/apis/api.blog.run/v1alpha1/trackers/*" ]
    verbs: [ "create" ]
  - nonResourceURLs: [ "/actuator/globalinfo", "/actuator/health", "/actuator/health/*", "/login/public-key" ]
    verbs: [ "get" ]
  - nonResourceURLs: [ "/apis/api.console.blog.run/v1alpha1/system/initialize" ]
    verbs: [ "create" ]
---
apiVersion: v1alpha1
kind: "Role"
metadata:
  name: role-template-public-apis
  labels:
    blog.run/role-template: "true"
    blog.run/hidden: "true"
rules:
  - apiGroups: [ "api.blog.run" ]
    resources: [ "*" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "api.content.blog.run" ]
    resources: [ "*" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "api.plugin.blog.run" ]
    resources: [ "*" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "api.notification.blog.run" ]
    resources: [ "subscriptions/unsubscribe" ]
    verbs: [ "get", "list" ]