apiVersion: v1alpha1
kind: "Role"
metadata:
  name: role-template-manage-tags
  labels:
    blog.run/role-template: "true"
    blog.run/hidden: "true"
  annotations:
    rbac.authorization.blog.run/dependencies: "[ \"role-template-view-tags\" ]"
rules:
  - apiGroups: [ "content.blog.run" ]
    resources: [ "tags" ]
    verbs: [ "*" ]
---
apiVersion: v1alpha1
kind: "Role"
metadata:
  name: role-template-view-tags
  labels:
    blog.run/role-template: "true"
    blog.run/hidden: "true"
rules:
  - apiGroups: [ "content.blog.run" ]
    resources: [ "tags" ]
    verbs: [ "get", "list" ]
