apiVersion: v1alpha1
kind: "Role"
metadata:
  name: role-template-manage-settings
  labels:
    blog.run/role-template: "true"
  annotations:
    rbac.authorization.blog.run/dependencies: "[ \"role-template-view-settings\", \"role-template-notifier-config\" ]"
    rbac.authorization.blog.run/module: "Settings Management"
    rbac.authorization.blog.run/display-name: "Setting Manage"
    rbac.authorization.blog.run/ui-permissions: |
      ["system:settings:manage", "system:notifier:configuration"]
rules:
  - apiGroups: [ "" ]
    resources: [ "settings" ]
    verbs: [ "create", "patch", "update", "delete", "deletecollection" ]
  - apiGroups: [ "api.console.blog.run" ]
    resources: [ "auth-providers/enable", "auth-providers/disable" ]
    verbs: [ "update" ]
---
apiVersion: v1alpha1
kind: "Role"
metadata:
  name: role-template-view-settings
  labels:
    blog.run/role-template: "true"
  annotations:
    rbac.authorization.blog.run/module: "Settings Management"
    rbac.authorization.blog.run/display-name: "Setting View"
    rbac.authorization.blog.run/ui-permissions: |
      ["system:settings:view"]
rules:
  - apiGroups: [ "" ]
    resources: [ "settings" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "api.console.blog.run" ]
    resources: [ "auth-providers" ]
    verbs: [ "get", "list" ]