/* tslint:disable */
/* eslint-disable */
/**
 * Blog Next API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from "../base";
// @ts-ignore
import { Policy } from "../models";
// @ts-ignore
import { PolicyList } from "../models";
/**
 * StorageBlogRunV1alpha1PolicyApi - axios parameter creator
 * @export
 */
export const StorageBlogRunV1alpha1PolicyApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     * Create storage.blog.run/v1alpha1/Policy
     * @param {Policy} [policy] Fresh policy
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createstorageBlogRunV1alpha1Policy: async (
      policy?: Policy,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/apis/storage.blog.run/v1alpha1/policies`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication BasicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication BearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        policy,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Delete storage.blog.run/v1alpha1/Policy
     * @param {string} name Name of policy
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deletestorageBlogRunV1alpha1Policy: async (
      name: string,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'name' is not null or undefined
      assertParamExists("deletestorageBlogRunV1alpha1Policy", "name", name);
      const localVarPath =
        `/apis/storage.blog.run/v1alpha1/policies/{name}`.replace(
          `{${"name"}}`,
          encodeURIComponent(String(name))
        );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication BasicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication BearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Get storage.blog.run/v1alpha1/Policy
     * @param {string} name Name of policy
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getstorageBlogRunV1alpha1Policy: async (
      name: string,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'name' is not null or undefined
      assertParamExists("getstorageBlogRunV1alpha1Policy", "name", name);
      const localVarPath =
        `/apis/storage.blog.run/v1alpha1/policies/{name}`.replace(
          `{${"name"}}`,
          encodeURIComponent(String(name))
        );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication BasicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication BearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * List storage.blog.run/v1alpha1/Policy
     * @param {Array<string>} [fieldSelector] Field selector for filtering.
     * @param {Array<string>} [labelSelector] Label selector for filtering.
     * @param {number} [page] The page number. Zero indicates no page.
     * @param {number} [size] Size of one page. Zero indicates no limit.
     * @param {Array<string>} [sort] Sort property and direction of the list result. Support sorting based on attribute name path.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    liststorageBlogRunV1alpha1Policy: async (
      fieldSelector?: Array<string>,
      labelSelector?: Array<string>,
      page?: number,
      size?: number,
      sort?: Array<string>,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/apis/storage.blog.run/v1alpha1/policies`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication BasicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication BearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (fieldSelector) {
        localVarQueryParameter["fieldSelector"] = fieldSelector;
      }

      if (labelSelector) {
        localVarQueryParameter["labelSelector"] = labelSelector;
      }

      if (page !== undefined) {
        localVarQueryParameter["page"] = page;
      }

      if (size !== undefined) {
        localVarQueryParameter["size"] = size;
      }

      if (sort) {
        localVarQueryParameter["sort"] = Array.from(sort);
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Update storage.blog.run/v1alpha1/Policy
     * @param {string} name Name of policy
     * @param {Policy} [policy] Updated policy
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updatestorageBlogRunV1alpha1Policy: async (
      name: string,
      policy?: Policy,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'name' is not null or undefined
      assertParamExists("updatestorageBlogRunV1alpha1Policy", "name", name);
      const localVarPath =
        `/apis/storage.blog.run/v1alpha1/policies/{name}`.replace(
          `{${"name"}}`,
          encodeURIComponent(String(name))
        );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication BasicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication BearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        policy,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * StorageBlogRunV1alpha1PolicyApi - functional programming interface
 * @export
 */
export const StorageBlogRunV1alpha1PolicyApiFp = function (
  configuration?: Configuration
) {
  const localVarAxiosParamCreator =
    StorageBlogRunV1alpha1PolicyApiAxiosParamCreator(configuration);
  return {
    /**
     * Create storage.blog.run/v1alpha1/Policy
     * @param {Policy} [policy] Fresh policy
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createstorageBlogRunV1alpha1Policy(
      policy?: Policy,
      options?: AxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Policy>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.createstorageBlogRunV1alpha1Policy(
          policy,
          options
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     * Delete storage.blog.run/v1alpha1/Policy
     * @param {string} name Name of policy
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deletestorageBlogRunV1alpha1Policy(
      name: string,
      options?: AxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.deletestorageBlogRunV1alpha1Policy(
          name,
          options
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     * Get storage.blog.run/v1alpha1/Policy
     * @param {string} name Name of policy
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getstorageBlogRunV1alpha1Policy(
      name: string,
      options?: AxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Policy>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getstorageBlogRunV1alpha1Policy(
          name,
          options
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     * List storage.blog.run/v1alpha1/Policy
     * @param {Array<string>} [fieldSelector] Field selector for filtering.
     * @param {Array<string>} [labelSelector] Label selector for filtering.
     * @param {number} [page] The page number. Zero indicates no page.
     * @param {number} [size] Size of one page. Zero indicates no limit.
     * @param {Array<string>} [sort] Sort property and direction of the list result. Support sorting based on attribute name path.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async liststorageBlogRunV1alpha1Policy(
      fieldSelector?: Array<string>,
      labelSelector?: Array<string>,
      page?: number,
      size?: number,
      sort?: Array<string>,
      options?: AxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<PolicyList>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.liststorageBlogRunV1alpha1Policy(
          fieldSelector,
          labelSelector,
          page,
          size,
          sort,
          options
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     * Update storage.blog.run/v1alpha1/Policy
     * @param {string} name Name of policy
     * @param {Policy} [policy] Updated policy
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updatestorageBlogRunV1alpha1Policy(
      name: string,
      policy?: Policy,
      options?: AxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Policy>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.updatestorageBlogRunV1alpha1Policy(
          name,
          policy,
          options
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
  };
};

/**
 * StorageBlogRunV1alpha1PolicyApi - factory interface
 * @export
 */
export const StorageBlogRunV1alpha1PolicyApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = StorageBlogRunV1alpha1PolicyApiFp(configuration);
  return {
    /**
     * Create storage.blog.run/v1alpha1/Policy
     * @param {StorageBlogRunV1alpha1PolicyApiCreatestorageBlogRunV1alpha1PolicyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createstorageBlogRunV1alpha1Policy(
      requestParameters: StorageBlogRunV1alpha1PolicyApiCreatestorageBlogRunV1alpha1PolicyRequest = {},
      options?: AxiosRequestConfig
    ): AxiosPromise<Policy> {
      return localVarFp
        .createstorageBlogRunV1alpha1Policy(requestParameters.policy, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Delete storage.blog.run/v1alpha1/Policy
     * @param {StorageBlogRunV1alpha1PolicyApiDeletestorageBlogRunV1alpha1PolicyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deletestorageBlogRunV1alpha1Policy(
      requestParameters: StorageBlogRunV1alpha1PolicyApiDeletestorageBlogRunV1alpha1PolicyRequest,
      options?: AxiosRequestConfig
    ): AxiosPromise<void> {
      return localVarFp
        .deletestorageBlogRunV1alpha1Policy(requestParameters.name, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Get storage.blog.run/v1alpha1/Policy
     * @param {StorageBlogRunV1alpha1PolicyApiGetstorageBlogRunV1alpha1PolicyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getstorageBlogRunV1alpha1Policy(
      requestParameters: StorageBlogRunV1alpha1PolicyApiGetstorageBlogRunV1alpha1PolicyRequest,
      options?: AxiosRequestConfig
    ): AxiosPromise<Policy> {
      return localVarFp
        .getstorageBlogRunV1alpha1Policy(requestParameters.name, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * List storage.blog.run/v1alpha1/Policy
     * @param {StorageBlogRunV1alpha1PolicyApiListstorageBlogRunV1alpha1PolicyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    liststorageBlogRunV1alpha1Policy(
      requestParameters: StorageBlogRunV1alpha1PolicyApiListstorageBlogRunV1alpha1PolicyRequest = {},
      options?: AxiosRequestConfig
    ): AxiosPromise<PolicyList> {
      return localVarFp
        .liststorageBlogRunV1alpha1Policy(
          requestParameters.fieldSelector,
          requestParameters.labelSelector,
          requestParameters.page,
          requestParameters.size,
          requestParameters.sort,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Update storage.blog.run/v1alpha1/Policy
     * @param {StorageBlogRunV1alpha1PolicyApiUpdatestorageBlogRunV1alpha1PolicyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updatestorageBlogRunV1alpha1Policy(
      requestParameters: StorageBlogRunV1alpha1PolicyApiUpdatestorageBlogRunV1alpha1PolicyRequest,
      options?: AxiosRequestConfig
    ): AxiosPromise<Policy> {
      return localVarFp
        .updatestorageBlogRunV1alpha1Policy(
          requestParameters.name,
          requestParameters.policy,
          options
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for createstorageBlogRunV1alpha1Policy operation in StorageBlogRunV1alpha1PolicyApi.
 * @export
 * @interface StorageBlogRunV1alpha1PolicyApiCreatestorageBlogRunV1alpha1PolicyRequest
 */
export interface StorageBlogRunV1alpha1PolicyApiCreatestorageBlogRunV1alpha1PolicyRequest {
  /**
   * Fresh policy
   * @type {Policy}
   * @memberof StorageBlogRunV1alpha1PolicyApiCreatestorageBlogRunV1alpha1Policy
   */
  readonly policy?: Policy;
}

/**
 * Request parameters for deletestorageBlogRunV1alpha1Policy operation in StorageBlogRunV1alpha1PolicyApi.
 * @export
 * @interface StorageBlogRunV1alpha1PolicyApiDeletestorageBlogRunV1alpha1PolicyRequest
 */
export interface StorageBlogRunV1alpha1PolicyApiDeletestorageBlogRunV1alpha1PolicyRequest {
  /**
   * Name of policy
   * @type {string}
   * @memberof StorageBlogRunV1alpha1PolicyApiDeletestorageBlogRunV1alpha1Policy
   */
  readonly name: string;
}

/**
 * Request parameters for getstorageBlogRunV1alpha1Policy operation in StorageBlogRunV1alpha1PolicyApi.
 * @export
 * @interface StorageBlogRunV1alpha1PolicyApiGetstorageBlogRunV1alpha1PolicyRequest
 */
export interface StorageBlogRunV1alpha1PolicyApiGetstorageBlogRunV1alpha1PolicyRequest {
  /**
   * Name of policy
   * @type {string}
   * @memberof StorageBlogRunV1alpha1PolicyApiGetstorageBlogRunV1alpha1Policy
   */
  readonly name: string;
}

/**
 * Request parameters for liststorageBlogRunV1alpha1Policy operation in StorageBlogRunV1alpha1PolicyApi.
 * @export
 * @interface StorageBlogRunV1alpha1PolicyApiListstorageBlogRunV1alpha1PolicyRequest
 */
export interface StorageBlogRunV1alpha1PolicyApiListstorageBlogRunV1alpha1PolicyRequest {
  /**
   * Field selector for filtering.
   * @type {Array<string>}
   * @memberof StorageBlogRunV1alpha1PolicyApiListstorageBlogRunV1alpha1Policy
   */
  readonly fieldSelector?: Array<string>;

  /**
   * Label selector for filtering.
   * @type {Array<string>}
   * @memberof StorageBlogRunV1alpha1PolicyApiListstorageBlogRunV1alpha1Policy
   */
  readonly labelSelector?: Array<string>;

  /**
   * The page number. Zero indicates no page.
   * @type {number}
   * @memberof StorageBlogRunV1alpha1PolicyApiListstorageBlogRunV1alpha1Policy
   */
  readonly page?: number;

  /**
   * Size of one page. Zero indicates no limit.
   * @type {number}
   * @memberof StorageBlogRunV1alpha1PolicyApiListstorageBlogRunV1alpha1Policy
   */
  readonly size?: number;

  /**
   * Sort property and direction of the list result. Support sorting based on attribute name path.
   * @type {Array<string>}
   * @memberof StorageBlogRunV1alpha1PolicyApiListstorageBlogRunV1alpha1Policy
   */
  readonly sort?: Array<string>;
}

/**
 * Request parameters for updatestorageBlogRunV1alpha1Policy operation in StorageBlogRunV1alpha1PolicyApi.
 * @export
 * @interface StorageBlogRunV1alpha1PolicyApiUpdatestorageBlogRunV1alpha1PolicyRequest
 */
export interface StorageBlogRunV1alpha1PolicyApiUpdatestorageBlogRunV1alpha1PolicyRequest {
  /**
   * Name of policy
   * @type {string}
   * @memberof StorageBlogRunV1alpha1PolicyApiUpdatestorageBlogRunV1alpha1Policy
   */
  readonly name: string;

  /**
   * Updated policy
   * @type {Policy}
   * @memberof StorageBlogRunV1alpha1PolicyApiUpdatestorageBlogRunV1alpha1Policy
   */
  readonly policy?: Policy;
}

/**
 * StorageBlogRunV1alpha1PolicyApi - object-oriented interface
 * @export
 * @class StorageBlogRunV1alpha1PolicyApi
 * @extends {BaseAPI}
 */
export class StorageBlogRunV1alpha1PolicyApi extends BaseAPI {
  /**
   * Create storage.blog.run/v1alpha1/Policy
   * @param {StorageBlogRunV1alpha1PolicyApiCreatestorageBlogRunV1alpha1PolicyRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorageBlogRunV1alpha1PolicyApi
   */
  public createstorageBlogRunV1alpha1Policy(
    requestParameters: StorageBlogRunV1alpha1PolicyApiCreatestorageBlogRunV1alpha1PolicyRequest = {},
    options?: AxiosRequestConfig
  ) {
    return StorageBlogRunV1alpha1PolicyApiFp(this.configuration)
      .createstorageBlogRunV1alpha1Policy(requestParameters.policy, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Delete storage.blog.run/v1alpha1/Policy
   * @param {StorageBlogRunV1alpha1PolicyApiDeletestorageBlogRunV1alpha1PolicyRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorageBlogRunV1alpha1PolicyApi
   */
  public deletestorageBlogRunV1alpha1Policy(
    requestParameters: StorageBlogRunV1alpha1PolicyApiDeletestorageBlogRunV1alpha1PolicyRequest,
    options?: AxiosRequestConfig
  ) {
    return StorageBlogRunV1alpha1PolicyApiFp(this.configuration)
      .deletestorageBlogRunV1alpha1Policy(requestParameters.name, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Get storage.blog.run/v1alpha1/Policy
   * @param {StorageBlogRunV1alpha1PolicyApiGetstorageBlogRunV1alpha1PolicyRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorageBlogRunV1alpha1PolicyApi
   */
  public getstorageBlogRunV1alpha1Policy(
    requestParameters: StorageBlogRunV1alpha1PolicyApiGetstorageBlogRunV1alpha1PolicyRequest,
    options?: AxiosRequestConfig
  ) {
    return StorageBlogRunV1alpha1PolicyApiFp(this.configuration)
      .getstorageBlogRunV1alpha1Policy(requestParameters.name, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * List storage.blog.run/v1alpha1/Policy
   * @param {StorageBlogRunV1alpha1PolicyApiListstorageBlogRunV1alpha1PolicyRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorageBlogRunV1alpha1PolicyApi
   */
  public liststorageBlogRunV1alpha1Policy(
    requestParameters: StorageBlogRunV1alpha1PolicyApiListstorageBlogRunV1alpha1PolicyRequest = {},
    options?: AxiosRequestConfig
  ) {
    return StorageBlogRunV1alpha1PolicyApiFp(this.configuration)
      .liststorageBlogRunV1alpha1Policy(
        requestParameters.fieldSelector,
        requestParameters.labelSelector,
        requestParameters.page,
        requestParameters.size,
        requestParameters.sort,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Update storage.blog.run/v1alpha1/Policy
   * @param {StorageBlogRunV1alpha1PolicyApiUpdatestorageBlogRunV1alpha1PolicyRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorageBlogRunV1alpha1PolicyApi
   */
  public updatestorageBlogRunV1alpha1Policy(
    requestParameters: StorageBlogRunV1alpha1PolicyApiUpdatestorageBlogRunV1alpha1PolicyRequest,
    options?: AxiosRequestConfig
  ) {
    return StorageBlogRunV1alpha1PolicyApiFp(this.configuration)
      .updatestorageBlogRunV1alpha1Policy(
        requestParameters.name,
        requestParameters.policy,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
